name: Build and Release
on:
  push:
    tags:
      - "v*.*.*"
      - feat/redm

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
      working-directory: web
      
    - name: Build
      run: pnpm build     
      working-directory: web

    - name: Create Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        id: auto_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "${{ env.RELEASE_VERSION }}"
          prerelease: false
          files: ox_inventory.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
